import { CurriculumCourse, CourseResult, PrerequisiteRule } from "./types";

export const demoCurriculum: CurriculumCourse[] = [
  {
    course_code: "MATH101",
    course_name: "Giải tích 1",
    credits: 3,
    expected_semester: 1,
    knowledge_block: "GENERAL",
    is_required: true,
  },
  {
    course_code: "PHYS101",
    course_name: "Vật lý đại cương 1",
    credits: 3,
    expected_semester: 1,
    knowledge_block: "GENERAL",
    is_required: true,
  },
  {
    course_code: "PROG101",
    course_name: "Nhập môn Lập trình",
    credits: 4,
    expected_semester: 1,
    knowledge_block: "SECTOR_CORE",
    is_required: true,
  },
  {
    course_code: "MATH102",
    course_name: "Giải tích 2",
    credits: 3,
    expected_semester: 2,
    knowledge_block: "GENERAL",
    is_required: true,
  },
  {
    course_code: "PROG102",
    course_name: "Kỹ thuật Lập trình",
    credits: 4,
    expected_semester: 2,
    knowledge_block: "SECTOR_CORE",
    is_required: true,
  },
  {
    course_code: "DSA201",
    course_name: "Cấu trúc dữ liệu và Giải thuật",
    credits: 4,
    expected_semester: 3,
    knowledge_block: "MAJOR_CORE",
    is_required: true,
  },
  {
    course_code: "DB201",
    course_name: "Cơ sở dữ liệu",
    credits: 3,
    expected_semester: 3,
    knowledge_block: "MAJOR_CORE",
    is_required: true,
  },
  {
    course_code: "OOP202",
    course_name: "Lập trình hướng đối tượng",
    credits: 4,
    expected_semester: 4,
    knowledge_block: "MAJOR_CORE",
    is_required: true,
  },
  {
    course_code: "DB202",
    course_name: "Hệ quản trị Cơ sở dữ liệu",
    credits: 3,
    expected_semester: 4,
    knowledge_block: "MAJOR_CORE",
    is_required: true,
  },
  {
    course_code: "OS301",
    course_name: "Hệ điều hành",
    credits: 3,
    expected_semester: 5,
    knowledge_block: "MAJOR_CORE",
    is_required: true,
  },
  {
    course_code: "CNPM302",
    course_name: "Công nghệ phần mềm",
    credits: 4,
    expected_semester: 5,
    knowledge_block: "MAJOR_CORE",
    is_required: true,
  },
  {
    course_code: "WEB303",
    course_name: "Lập trình Web nâng cao",
    credits: 3,
    expected_semester: 5,
    knowledge_block: "SPECIALIZED",
    is_required: false,
  },
  {
    course_code: "MOBILE304",
    course_name: "Lập trình thiết bị di động",
    credits: 3,
    expected_semester: 6,
    knowledge_block: "SPECIALIZED",
    is_required: false,
  },
  {
    course_code: "CLOUD305",
    course_name: "Điện toán đám mây",
    credits: 3,
    expected_semester: 6,
    knowledge_block: "SPECIALIZED",
    is_required: true,
  },
  {
    course_code: "INTERN401",
    course_name: "Thực tập tốt nghiệp",
    credits: 4,
    expected_semester: 7,
    knowledge_block: "SPECIALIZED",
    is_required: true,
  },
  {
    course_code: "PROJECT402",
    course_name: "Đồ án chuyên ngành",
    credits: 4,
    expected_semester: 7,
    knowledge_block: "SPECIALIZED",
    is_required: true,
  },
  {
    course_code: "THESIS403",
    course_name: "Khóa luận tốt nghiệp",
    credits: 10,
    expected_semester: 8,
    knowledge_block: "SPECIALIZED",
    is_required: true,
  },
];

export const demoResults: CourseResult[] = [
  { id: "1", course_code: "MATH101", course_name: "Giải tích 1", credits: 3, score_4: 3.5, status: "PASSED" },
  { id: "2", course_code: "PHYS101", course_name: "Vật lý đại cương 1", credits: 3, score_4: 2.0, status: "PASSED" },
  { id: "3", course_code: "PROG101", course_name: "Nhập môn Lập trình", credits: 4, score_4: 3.0, status: "PASSED" },
  { id: "4", course_code: "MATH102", course_name: "Giải tích 2", credits: 3, score_4: 2.5, status: "PASSED" },
  { id: "5", course_code: "PROG102", course_name: "Kỹ thuật Lập trình", credits: 4, score_4: 3.5, status: "PASSED" },
  { id: "6", course_code: "DSA201", course_name: "Cấu trúc dữ liệu và Giải thuật", credits: 4, score_4: null, status: "STUDYING" },
  { id: "7", course_code: "DB201", course_name: "Cơ sở dữ liệu", credits: 3, score_4: null, status: "STUDYING" },
];

export const demoPrereqs: PrerequisiteRule[] = [
  { course_code: "PROG102", prerequisite_course_code: "PROG101" },
  { course_code: "DSA201", prerequisite_course_code: "PROG102" },
  { course_code: "OOP202", prerequisite_course_code: "PROG102" },
  { course_code: "DB202", prerequisite_course_code: "DB201" },
  { course_code: "CNPM302", prerequisite_course_code: "DSA201" },
  { course_code: "PROJECT402", prerequisite_course_code: "CNPM302" },
  { course_code: "THESIS403", prerequisite_course_code: "PROJECT402" },
];
